
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 17 18:18:14 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 41;
  public static final int CONST = 15;
  public static final int QUESTIONMARK = 38;
  public static final int CASE = 13;
  public static final int NOTEQUAL = 24;
  public static final int LPAREN = 39;
  public static final int CONTINUE = 6;
  public static final int FOR = 7;
  public static final int BIGGEROREQUALTHAN = 26;
  public static final int MINUS = 19;
  public static final int CHARACTER = 48;
  public static final int RPAREN = 40;
  public static final int OROR = 30;
  public static final int SMALLEROREQUALTHAN = 28;
  public static final int SEMICOLON = 34;
  public static final int SMALLERTHAN = 27;
  public static final int BOOL = 47;
  public static final int COMMA = 36;
  public static final int INC = 32;
  public static final int EQUALEQUAL = 23;
  public static final int DIV = 21;
  public static final int ANDAND = 29;
  public static final int PLUS = 18;
  public static final int IF = 4;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 42;
  public static final int EQUAL = 31;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int MUL = 20;
  public static final int NUMBER = 46;
  public static final int MOD = 22;
  public static final int IDENT = 45;
  public static final int BREAK = 5;
  public static final int VOID = 11;
  public static final int SWITCH = 12;
  public static final int COLON = 35;
  public static final int LBRACE = 43;
  public static final int ELSE = 3;
  public static final int ENUM = 14;
  public static final int READ = 9;
  public static final int RBRACE = 44;
  public static final int PROG = 2;
  public static final int BIGGERTHAN = 25;
  public static final int DEC = 33;
  public static final int PRINT = 8;
  public static final int LENGTH = 17;
}

