
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 31 23:29:22 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ENUM = 11;
  public static final int LBRACE = 3;
  public static final int CHARACTER = 15;
  public static final int IDENT = 12;
  public static final int BOOL = 14;
  public static final int NUMBER = 13;
  public static final int PROG = 2;
  public static final int EQUAL = 7;
  public static final int EOF = 0;
  public static final int RBRACKET = 10;
  public static final int COMMA = 8;
  public static final int error = 1;
  public static final int SEMICOLON = 6;
  public static final int LBRACKET = 9;
  public static final int RBRACE = 4;
  public static final int CONST = 5;
}

