package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import org.apache.log4j.*;
import rs.ac.bg.etf.pp1.ast.*;

/*----------------------------------------------------------------------------------------------------------------*/

parser code {:


	boolean errorDetected;
	
	Logger log = Logger.getLogger(getClass());
   
   
    // slede redefinisani metodi za prijavu gresaka radi izmene teksta poruke
     
    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
      done_parsing();
      report_error(message, info);
    }
  
    public void syntax_error(Symbol cur_token) {
        report_error("\nSintaksna greska", cur_token);
    }
  
    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        report_fatal_error("Fatalna greska, parsiranje se ne moze nastaviti", cur_token);
    }

    public void report_error(String message, Object info) {
    	errorDetected = true;
    	StringBuilder msg = new StringBuilder(message); 
    	if (info instanceof Symbol)
            msg.append (" na liniji ").append(((Symbol)info).left);
        log.error(msg.toString());
    }
    
:}

/*----------------------------------------------------------------------------------------------------------------*/

init with {:
	errorDetected = false;
:}

/*----------------------------------------------------------------------------------------------------------------*/

scan with {:
	Symbol s = this.getScanner().next_token();
	if (s != null && s.value != null) 
		log.info(s.toString() + " " + s.value.toString());
	return s;
:}

/*----------------------------------------------------------------------------------------------------------------*/

terminal PROG;
terminal LBRACE;
terminal RBRACE;
terminal CONST;
terminal SEMICOLON;
terminal EQUAL;
terminal COMMA;
terminal LBRACKET;
terminal RBRACKET;
terminal ENUM;
terminal String IDENT;
terminal Integer NUMBER;
terminal Integer BOOL;
terminal Character CHARACTER;

nonterminal Program;
nonterminal ConstVarEnumList;
nonterminal MethodDeclList;
nonterminal ConstDeclList;
nonterminal VarDeclList;
nonterminal EnumDeclList;
nonterminal Type;
nonterminal ConstDecl;
nonterminal ConstDeclMore;
nonterminal Constant;
nonterminal VarDecl;
nonterminal VarDeclMore;
nonterminal EnumDecl;
nonterminal EnumDeclMore;

/*----------------------------------------------------------------------------------------------------------------*/

/* Program = "program" ident {ConstDecl | VarDecl | EnumDecl } "{" {MethodDecl} "}" */

Program ::= (Program) PROG IDENT ConstVarEnumList LBRACE MethodDeclList RBRACE;

/*----------------------------------------------------------------------------------------------------------------*/

ConstVarEnumList ::= (ConstVarEnumList_Const) ConstVarEnumList ConstDeclList	
					 |
					 (ConstVarEnumList_Var) ConstVarEnumList VarDeclList
					 |
					 (ConstVarEnumList_Enum) ConstVarEnumList EnumDeclList
					 |
					 (ConstVarEnumList_epsilon) /* epsilon */
					 ; 

/*----------------------------------------------------------------------------------------------------------------*/

/* ConstDecl = "const" Type ident"="(numConst | charConst | boolConst) {, ident "=" (numConst | charConst | boolConst)} ";" */

ConstDeclList ::= (ConstDeclList) CONST Type ConstDecl ConstDeclMore SEMICOLON;

ConstDecl ::= (ConstDecl) IDENT EQUAL Constant;

ConstDeclMore ::= (ConstDeclMore_comma) COMMA ConstDecl ConstDeclMore
				|
				(ConstDeclMore_epsilon) /* epsilon */
				;

Constant ::= 	(Constant_number) NUMBER
				|
				(Constant_character) CHARACTER
				|
				(Constant_bool) BOOL
				;
/*----------------------------------------------------------------------------------------------------------------*/

/* VarDecl = Type ident ["[" "]"] {"," ident ["[" "]"]} ";" */

VarDeclList ::= (VarDeclList) Type VarDecl VarDeclMore SEMICOLON;


VarDecl ::= (VarDecl_var) IDENT  
			|
			(VarDecl_array) IDENT LBRACKET RBRACKET
			; 


VarDeclMore ::= (VarDeclMore_comma) COMMA VarDecl VarDeclMore 
				|
				(VarDeclMore_epsilon) /* epsilon */
				; 
				
/*----------------------------------------------------------------------------------------------------------------*/

/* EnumDecl = "enum" ident "{" ident ["=" numConst] {"," ident ["=" numConst]} "}" */

EnumDeclList ::= (EnumDeclList) ENUM IDENT LBRACE EnumDecl EnumDeclMore SEMICOLON;

EnumDecl ::= (EnumDecl_var) IDENT
			 |
			 (EnumDecl_equal) IDENT EQUAL NUMBER 
			 ;
			 
EnumDeclMore ::= (EnumDeclMore_comma) COMMA EnumDecl EnumDeclMore
				 |
				 (EnumDeclMore_epsilon) /* epsilon */
				 ;

/*----------------------------------------------------------------------------------------------------------------*/

Type ::= (Type) IDENT;

/*----------------------------------------------------------------------------------------------------------------*/
